title: "邻家书生的创作空间"
baseurl: ""
url: "https://linjiashusheng.github.io"

# 使用蓝绿色的Cayman主题
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# 主题个性化设置 (可选)
cayman:
  skin: light  # light为明亮蓝绿色，dark为深色模式
